kind: Service
apiVersion: v1
metadata:
  name: nodejs-service-canary
spec:
  type: NodePort
  selector:
    app: nodejs-app
    track: canary
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment-canary
  labels:
    app: nodejs-app
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: nodejs-app
      track: canary
  template:
    metadata:
      labels:
        app: nodejs-app
        track: canary
    spec:
      containers:
      - name: nodejs-app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
